import { Content } from './content.types';

export const CONTENT: Content = {
  pt: {
    nav: {
      about: 'Sobre',
      skills: 'Skills',
      xp: 'Experiência',
      edu: 'Educação',
      blog: 'Blog',
      contact: 'Contato',
      certs: 'Certificados',
      projects: 'Projetos',
    },
    hero: {
      eyebrow: 'Disponível para projetos · 2026',
      role: 'Desenvolvedor Fullstack',
      l1: 'BRUNO',
      l2: 'NYLAND',
      l3: 'FULLSTACK',
      l4: 'DEV',
      foot1l: 'Localizado em',
      foot1v: 'Brasil — UTC-3',
      foot2l: 'Stack principal',
      foot2v: 'Python · TS · React',
      foot3l: 'Desde',
      foot3v: '2010 / 15+ anos',
      foot4: 'Role ↓',
      metaTitle: 'EM ATIVIDADE',
      metaSub: 'Avaliador na CAIXA · Dev independente',
    },
    about: {
      num: '(01)',
      title: 'Sobre',
      lead: [
        'Construo sistemas web ',
        { em: 'do banco de dados ao pixel' },
        '. 15+ anos de código, fluente em ',
        { em: 'Python, TypeScript, C++ e C#' },
        ', com forte foco em automação, dados e produtos completos.',
      ],
      p1: 'Formado em Ciências Contábeis, atuo há 11 anos como avaliador de penhor na CAIXA. Em paralelo desenvolvo software de forma independente — produtos para web, automações com Selenium e Requests, pipelines de dados com Pandas/Numpy e interfaces modernas em React/Angular.',
      p2: 'Gosto de problemas que misturam técnica, negócio e visual. Trabalho com sites institucionais (Django/Wagtail), APIs (FastAPI), aplicações reativas e ferramentas internas que ninguém vê — mas todo mundo usa.',
      stats: [
        { n: '15', sup: '+', l: 'Anos programando' },
        { n: '11', sup: 'anos', l: 'CAIXA · Penhor' },
        { n: '40', sup: '+', l: 'Projetos entregues' },
        { n: '07', sup: 'stacks', l: 'Linguagens fluentes' },
      ],
    },
    skills: {
      num: '(02)',
      title: 'Stack',
      groups: [
        { cat: 'Linguagens', items: ['Python', 'JavaScript / TypeScript', 'C++', 'C#'] },
        { cat: 'Frameworks', items: ['Django / Wagtail', 'FastAPI', 'React', 'Angular'] },
        {
          cat: 'Dados & Automação',
          items: ['Pandas / NumPy', 'Selenium', 'Requests', 'ETL pipelines'],
        },
        { cat: 'Ferramentas', items: ['PostgreSQL', 'Docker', 'Git / CI', 'Linux'] },
      ],
    },
    work: {
      num: '(03)',
      title: 'Projetos selecionados',
      cta: 'Ver projeto',
      all: 'Ver todos os projetos',
      empty: 'Nenhum projeto em destaque no momento.',
    },
    xp: {
      num: '(04)',
      title: 'Experiência',
      totalLabel: 'Tempo total',
      cnpjLabel: 'CNPJ',
      presentLabel: 'Atual',
      companies: [
        {
          name: 'CAIXA Econômica Federal',
          cnpj: '00.360.305/0001-05',
          from: '06/05/2011',
          to: 'Atual',
          roles: [
            { from: '03/02/2014', to: 'Atual', role: 'Avaliador de Penhor' },
            {
              from: '11/02/2021',
              to: '02/05/2023',
              role: 'Substituto Eventual Gerente de Varejo',
            },
            { from: '08/04/2024', to: '19/04/2024', role: 'Gerente de Varejo S.E' },
            { from: '15/02/2024', to: '27/02/2024', role: 'Gerente de Varejo S.E' },
            { from: '08/09/2021', to: '17/09/2021', role: 'Gerente de Varejo S.E' },
            { from: '10/01/2013', to: '02/02/2014', role: 'Caixa Executivo' },
            { from: '06/05/2011', to: '09/01/2013', role: 'Técnico Bancário' },
          ],
        },
        {
          name: 'Sindicato dos Empregados em Estabelecimentos Bancários de Ponta Porã/MS',
          cnpj: '03.890.670/0001-19',
          from: '01/07/2024',
          to: 'Atual',
          roles: [
            {
              from: '01/07/2024',
              to: 'Atual',
              role: 'Desenvolvedor FullStack · Contrato de prestação de serviços',
            },
          ],
        },
        {
          name: 'Empresa de Apoio à Educação Douradense Ltda',
          cnpj: '08.989.598/0001-03',
          from: '01/08/2009',
          to: '20/04/2011',
          roles: [
            {
              from: '01/08/2009',
              to: '20/04/2011',
              role: 'Técnico de Manutenção Eletrônica · Professor de Informática',
            },
          ],
        },
      ],
    },
    edu: {
      num: '(05)',
      title: 'Educação Formal',
      statusOngoing: 'Cursando',
      statusDone: 'Concluído',
      dateOngoingLabel: 'Previsão de conclusão',
      dateDoneLabel: 'Conclusão',
      kindLabel: 'Tipo',
      workloadLabel: 'Carga horária',
      cnpjLabel: 'CNPJ',
      validationLabel: 'Validação',
      documentLabel: 'Diploma',
      items: [
        {
          status: 'ongoing',
          title: 'MBA em IA e Business Analytics',
          kind: 'Pós-Graduação Lato Sensu',
          institution: 'UNIGRAN Educacional',
          cnpj: '03.361.110/0001-77',
          date: '30/10/2026',
          workload: '464 horas',
        },
        {
          status: 'ongoing',
          title: 'Bacharelado em Engenharia de Software',
          kind: 'Bacharelado',
          institution: 'CESUMAR — Centro de Ensino Superior de Maringá Ltda',
          cnpj: '79.265.617/0001-99',
          date: '30/07/2028',
          workload: '2.980 horas',
        },
        {
          status: 'done',
          title: 'Bacharelado em Ciências Contábeis',
          kind: 'Bacharelado',
          institution: 'UNIGRAN Educacional',
          cnpj: '03.361.110/0001-77',
          date: '24/01/2026',
          workload: '3.210 horas',
          validation: 'https://unigran.webapp.abaris.com.br/diploma/0673.0673.329f03f0b1f5',
          url: 'docs/diploma_ciencias_contabeis.pdf',
        },
      ],
    },
    blog: {
      num: '(06)',
      title: 'Escrita recente',
      cta: 'Ler',
      all: 'Ver todos os posts',
      empty: 'Nenhum post em destaque no momento.',
    },
    blogPage: {
      title: 'Blog',
      lead: 'Notas sobre desenvolvimento, dados, automação e carreira.',
      searchPlaceholder: 'Buscar por título, tema ou palavra-chave…',
      allTags: 'Todos os temas',
      results: 'post(s)',
      empty: 'Nenhum post encontrado com esses filtros.',
      loading: 'Carregando posts…',
      error: 'Não foi possível carregar os posts. Tente novamente.',
      readMore: 'Ler post',
      backToBlog: '← Blog',
      backToHome: '← Início',
      notFound: 'Post não encontrado.',
    },
    contact: {
      num: '(07)',
      title: 'Contato',
      big: ['VAMOS ', { em: 'construir ' }, 'algo', { outline: 'real' }],
      items: [
        { l: 'E-mail', v: 'contato@brunonyland.com', href: 'mailto:contato@brunonyland.com' },
        { l: 'GitHub', v: 'github.com/brunonyland', href: 'https://github.com/brunonyland' },
        {
          l: 'LinkedIn',
          v: 'linkedin.com/in/brunonyland',
          href: 'https://linkedin.com/in/brunonyland',
        },
        { l: 'Site', v: 'brunonyland.com', href: 'https://brunonyland.com' },
      ],
    },
    certs: {
      num: '(08)',
      title: 'Certificados',
      lead: 'Cursos e especializações concluídos — formação contínua em desenvolvimento, dados e automação.',
      back: '← Início',
      statHours: 'Horas estudadas',
      statCourses: 'Certificados',
      statTopics: 'Temas',
      byTopicTitle: 'Horas por tema',
      searchPlaceholder: 'Buscar por curso, plataforma ou tema…',
      allPlatforms: 'Todas as plataformas',
      allTopics: 'Todos os temas',
      allLanguages: 'Todos os idiomas',
      results: 'resultado(s)',
      empty: 'Nenhum certificado encontrado com esses filtros.',
      loading: 'Carregando certificados…',
      error: 'Não foi possível carregar os certificados. Tente novamente.',
      viewPdf: 'Ver PDF',
      validate: 'Validar',
    },
    projectsPage: {
      num: '(03)',
      title: 'Projetos',
      lead: 'Sites, sistemas e infra que desenhei, construí e opero — do backend ao deploy.',
      searchPlaceholder: 'Buscar por título, categoria ou tecnologia…',
      allCategories: 'Todas as categorias',
      allTags: 'Todas as tecnologias',
      results: 'projeto(s)',
      empty: 'Nenhum projeto encontrado com esses filtros.',
      loading: 'Carregando projetos…',
      error: 'Não foi possível carregar os projetos. Tente novamente.',
      visit: 'Acessar',
      repo: 'Código',
      readArticle: 'Ler artigo',
      client: 'Cliente',
      role: 'Papel',
      statusLive: 'No ar',
      statusArchived: 'Arquivo',
      back: '← Início',
    },
    foot: { l: '© 2026 Bruno Nyland', r: 'Construído com Angular, GSAP e Three.js' },
    loader: {
      top1: 'BRUNO NYLAND',
      top2: 'PORTFOLIO 2026',
      foot1: 'CARREGANDO RECURSOS',
      foot2: 'v1.0',
    },
    seo: {
      home: {
        title: 'Bruno Nyland — Desenvolvedor Fullstack',
        desc: 'Portfólio de Bruno Nyland — desenvolvedor fullstack com 15+ anos em Python, TypeScript e dados.',
      },
      certs: {
        title: 'Certificados — Bruno Nyland',
        desc: 'Banco de certificados de Bruno Nyland: cursos e especializações em desenvolvimento, dados e automação, com horas estudadas por tema.',
      },
      blog: {
        title: 'Blog — Bruno Nyland',
        desc: 'Artigos de Bruno Nyland sobre desenvolvimento, dados, automação e carreira em tecnologia.',
      },
      projects: {
        title: 'Projetos — Bruno Nyland',
        desc: 'Sites, sistemas e infraestrutura que Bruno Nyland desenhou, construiu e opera — do backend ao deploy.',
      },
    },
  },
  en: {
    nav: {
      about: 'About',
      skills: 'Stack',
      xp: 'Experience',
      edu: 'Education',
      blog: 'Journal',
      contact: 'Contact',
      certs: 'Certificates',
      projects: 'Projects',
    },
    hero: {
      eyebrow: 'Available for projects · 2026',
      role: 'Fullstack Developer',
      l1: 'BRUNO',
      l2: 'NYLAND',
      l3: 'FULLSTACK',
      l4: 'DEV',
      foot1l: 'Based in',
      foot1v: 'Brazil — UTC-3',
      foot2l: 'Main stack',
      foot2v: 'Python · TS · React',
      foot3l: 'Coding since',
      foot3v: '2010 / 15+ years',
      foot4: 'Scroll ↓',
      metaTitle: 'CURRENTLY',
      metaSub: 'Appraiser at CAIXA · Indie dev',
    },
    about: {
      num: '(01)',
      title: 'About',
      lead: [
        'I build web systems ',
        { em: 'from database to pixel' },
        '. 15+ years writing code, fluent in ',
        { em: 'Python, TypeScript, C++ and C#' },
        ', with a sharp focus on automation, data and end-to-end products.',
      ],
      p1: 'Accounting major, I’ve worked for 11 years as a pawn appraiser at CAIXA, Brazil’s federal bank. In parallel I build software independently — institutional sites, automation with Selenium and Requests, data pipelines with Pandas/NumPy and modern UIs in React/Angular.',
      p2: 'I like problems mixing technique, business and craft. I work on Django/Wagtail sites, FastAPI services, reactive apps and internal tools nobody sees — but everyone uses.',
      stats: [
        { n: '15', sup: '+', l: 'Years coding' },
        { n: '11', sup: 'yrs', l: 'CAIXA · Appraisal' },
        { n: '40', sup: '+', l: 'Projects shipped' },
        { n: '07', sup: 'stacks', l: 'Fluent languages' },
      ],
    },
    skills: {
      num: '(02)',
      title: 'Stack',
      groups: [
        { cat: 'Languages', items: ['Python', 'JavaScript / TypeScript', 'C++', 'C#'] },
        { cat: 'Frameworks', items: ['Django / Wagtail', 'FastAPI', 'React', 'Angular'] },
        {
          cat: 'Data & Automation',
          items: ['Pandas / NumPy', 'Selenium', 'Requests', 'ETL pipelines'],
        },
        { cat: 'Tooling', items: ['PostgreSQL', 'Docker', 'Git / CI', 'Linux'] },
      ],
    },
    work: {
      num: '(03)',
      title: 'Selected work',
      cta: 'View project',
      all: 'See all projects',
      empty: 'No featured projects right now.',
    },
    xp: {
      num: '(04)',
      title: 'Experience',
      totalLabel: 'Total time',
      cnpjLabel: 'CNPJ',
      presentLabel: 'Present',
      companies: [
        {
          name: 'CAIXA Federal Bank',
          cnpj: '00.360.305/0001-05',
          from: '06/05/2011',
          to: 'Present',
          roles: [
            { from: '03/02/2014', to: 'Present', role: 'Pawn Appraiser' },
            {
              from: '11/02/2021',
              to: '02/05/2023',
              role: 'Acting Retail Manager (substitute appointments)',
            },
            { from: '08/04/2024', to: '19/04/2024', role: 'Substitution: Retail Manager' },
            { from: '15/02/2024', to: '27/02/2024', role: 'Substitution: Retail Manager' },
            { from: '08/09/2021', to: '17/09/2021', role: 'Substitution: Retail Manager' },
            { from: '10/01/2013', to: '02/02/2014', role: 'Executive Teller' },
            { from: '06/05/2011', to: '09/01/2013', role: 'Bank Technician' },
          ],
        },
        {
          name: 'Bank Workers Union of Ponta Porã – MS',
          cnpj: '03.890.670/0001-19',
          from: '01/07/2024',
          to: 'Present',
          roles: [
            {
              from: '01/07/2024',
              to: 'Present',
              role: 'Fullstack Developer · Service contract',
            },
          ],
        },
        {
          name: 'Dourados Education Support Company Ltda',
          cnpj: '08.989.598/0001-03',
          from: '01/08/2009',
          to: '20/04/2011',
          roles: [
            {
              from: '01/08/2009',
              to: '20/04/2011',
              role: 'Electronics Maintenance Technician · IT Teacher',
            },
          ],
        },
      ],
    },
    edu: {
      num: '(05)',
      title: 'Formal Education',
      statusOngoing: 'In progress',
      statusDone: 'Completed',
      dateOngoingLabel: 'Expected completion',
      dateDoneLabel: 'Completed on',
      kindLabel: 'Degree',
      workloadLabel: 'Workload',
      cnpjLabel: 'CNPJ',
      validationLabel: 'Verify',
      documentLabel: 'Diploma',
      items: [
        {
          status: 'ongoing',
          title: 'MBA in AI & Business Analytics',
          kind: 'Postgraduate (Lato Sensu)',
          institution: 'UNIGRAN Educacional',
          cnpj: '03.361.110/0001-77',
          date: '30/10/2026',
          workload: '464 hours',
        },
        {
          status: 'ongoing',
          title: 'Bachelor of Software Engineering',
          kind: "Bachelor's Degree",
          institution: 'CESUMAR — Centro de Ensino Superior de Maringá Ltda',
          cnpj: '79.265.617/0001-99',
          date: '30/07/2028',
          workload: '2,980 hours',
        },
        {
          status: 'done',
          title: 'Bachelor of Accounting Sciences',
          kind: "Bachelor's Degree",
          institution: 'UNIGRAN Educacional',
          cnpj: '03.361.110/0001-77',
          date: '24/01/2026',
          workload: '3,210 hours',
          validation: 'https://unigran.webapp.abaris.com.br/diploma/0673.0673.329f03f0b1f5',
          url: 'docs/diploma_ciencias_contabeis.pdf',
        },
      ],
    },
    blog: {
      num: '(06)',
      title: 'Recent writing',
      cta: 'Read',
      all: 'See all posts',
      empty: 'No featured posts right now.',
    },
    blogPage: {
      title: 'Blog',
      lead: 'Notes on development, data, automation and career.',
      searchPlaceholder: 'Search by title, topic or keyword…',
      allTags: 'All topics',
      results: 'post(s)',
      empty: 'No posts match these filters.',
      loading: 'Loading posts…',
      error: 'Could not load the posts. Please try again.',
      readMore: 'Read post',
      backToBlog: '← Blog',
      backToHome: '← Home',
      notFound: 'Post not found.',
    },
    contact: {
      num: '(07)',
      title: 'Contact',
      big: ['LET’S ', { em: 'build ' }, 'something', { outline: 'real' }],
      items: [
        { l: 'E-mail', v: 'contato@brunonyland.com', href: 'mailto:contato@brunonyland.com' },
        { l: 'GitHub', v: 'github.com/brunonyland', href: 'https://github.com/brunonyland' },
        {
          l: 'LinkedIn',
          v: 'linkedin.com/in/brunonyland',
          href: 'https://linkedin.com/in/brunonyland',
        },
        { l: 'Website', v: 'brunonyland.com', href: 'https://brunonyland.com' },
      ],
    },
    certs: {
      num: '(08)',
      title: 'Certificates',
      lead: 'Completed courses and specializations — continuous learning in development, data and automation.',
      back: '← Home',
      statHours: 'Hours studied',
      statCourses: 'Certificates',
      statTopics: 'Topics',
      byTopicTitle: 'Hours per topic',
      searchPlaceholder: 'Search by course, platform or topic…',
      allPlatforms: 'All platforms',
      allTopics: 'All topics',
      allLanguages: 'All languages',
      results: 'result(s)',
      empty: 'No certificates match these filters.',
      loading: 'Loading certificates…',
      error: 'Could not load the certificates. Please try again.',
      viewPdf: 'View PDF',
      validate: 'Verify',
    },
    projectsPage: {
      num: '(03)',
      title: 'Projects',
      lead: 'Sites, systems and infrastructure I designed, built and operate — from backend to deploy.',
      searchPlaceholder: 'Search by title, category or technology…',
      allCategories: 'All categories',
      allTags: 'All technologies',
      results: 'project(s)',
      empty: 'No projects match these filters.',
      loading: 'Loading projects…',
      error: 'Could not load the projects. Please try again.',
      visit: 'Visit',
      repo: 'Code',
      readArticle: 'Read article',
      client: 'Client',
      role: 'Role',
      statusLive: 'Live',
      statusArchived: 'Archived',
      back: '← Home',
    },
    foot: { l: '© 2026 Bruno Nyland', r: 'Built with Angular, GSAP and Three.js' },
    loader: {
      top1: 'BRUNO NYLAND',
      top2: 'PORTFOLIO 2026',
      foot1: 'LOADING ASSETS',
      foot2: 'v1.0',
    },
    seo: {
      home: {
        title: 'Bruno Nyland — Fullstack Developer',
        desc: 'Portfolio of Bruno Nyland — fullstack developer with 15+ years in Python, TypeScript and data.',
      },
      certs: {
        title: 'Certificates — Bruno Nyland',
        desc: 'Bruno Nyland’s certificates: courses and specializations in development, data and automation, with hours studied per topic.',
      },
      blog: {
        title: 'Blog — Bruno Nyland',
        desc: 'Articles by Bruno Nyland on development, data, automation and a career in technology.',
      },
      projects: {
        title: 'Projects — Bruno Nyland',
        desc: 'Sites, systems and infrastructure Bruno Nyland designed, built and operates — from backend to deploy.',
      },
    },
  },
};
