import { Content } from './content.types';

export const CONTENT: Content = {
  pt: {
    nav: {
      about: 'Sobre',
      skills: 'Skills',
      work: 'Projetos',
      xp: 'Experiência',
      edu: 'Educação',
      blog: 'Blog',
      contact: 'Contato',
    },
    hero: {
      eyebrow: 'Disponível para projetos · 2026',
      role: 'Desenvolvedor Fullstack',
      l1: 'BRUNO',
      l2: 'NYLAND',
      l3: 'FULLSTACK',
      l4: 'DEV',
      foot1l: 'Localizado em',
      foot1v: 'Brasil — UTC-3',
      foot2l: 'Stack principal',
      foot2v: 'Python · TS · React',
      foot3l: 'Desde',
      foot3v: '2010 / 15+ anos',
      foot4: 'Role ↓',
      metaTitle: 'EM ATIVIDADE',
      metaSub: 'Avaliador na CAIXA · Dev independente',
    },
    about: {
      num: '(01)',
      title: 'Sobre',
      lead: [
        'Construo sistemas web ',
        { em: 'do banco de dados ao pixel' },
        '. 15+ anos de código, fluente em ',
        { em: 'Python, TypeScript, C++ e C#' },
        ', com forte foco em automação, dados e produtos completos.',
      ],
      p1: 'Formado em Ciências Contábeis, atuo há 11 anos como avaliador de penhor na CAIXA. Em paralelo desenvolvo software de forma independente — produtos para web, automações com Selenium e Requests, pipelines de dados com Pandas/Numpy e interfaces modernas em React/Angular.',
      p2: 'Gosto de problemas que misturam técnica, negócio e visual. Trabalho com sites institucionais (Django/Wagtail), APIs (FastAPI), aplicações reativas e ferramentas internas que ninguém vê — mas todo mundo usa.',
      stats: [
        { n: '15', sup: '+', l: 'Anos programando' },
        { n: '11', sup: 'anos', l: 'CAIXA · Penhor' },
        { n: '40', sup: '+', l: 'Projetos entregues' },
        { n: '07', sup: 'stacks', l: 'Linguagens fluentes' },
      ],
    },
    skills: {
      num: '(02)',
      title: 'Stack',
      groups: [
        { cat: 'Linguagens', items: ['Python', 'JavaScript / TypeScript', 'C++', 'C#'] },
        { cat: 'Frameworks', items: ['Django / Wagtail', 'FastAPI', 'React', 'Angular'] },
        {
          cat: 'Dados & Automação',
          items: ['Pandas / NumPy', 'Selenium', 'Requests', 'ETL pipelines'],
        },
        { cat: 'Ferramentas', items: ['PostgreSQL', 'Docker', 'Git / CI', 'Linux'] },
      ],
    },
    work: {
      num: '(03)',
      title: 'Projetos selecionados',
      items: [
        {
          t: 'Sistema de Avaliação',
          y: '2025',
          k: 'Fintech / Interno',
          tags: ['Django', 'Postgres', 'Wagtail'],
          ph: 'Print do dashboard',
        },
        {
          t: 'Bot de Coleta',
          y: '2024',
          k: 'Automação',
          tags: ['Python', 'Selenium', 'Pandas'],
          ph: 'Diagrama de fluxo',
        },
        {
          t: 'API de Catálogo',
          y: '2024',
          k: 'Backend',
          tags: ['FastAPI', 'Redis', 'Docker'],
          ph: 'Spec da API',
        },
        {
          t: 'Dashboard React',
          y: '2023',
          k: 'Frontend',
          tags: ['React', 'TS', 'D3'],
          ph: 'Mockup do painel',
        },
        {
          t: 'Pipeline ETL',
          y: '2023',
          k: 'Dados',
          tags: ['Python', 'Airflow', 'S3'],
          ph: 'Topologia do pipe',
        },
        {
          t: 'Tooling Desktop',
          y: '2022',
          k: 'Interno',
          tags: ['C#', 'WPF'],
          ph: 'Captura da ferramenta',
        },
      ],
    },
    xp: {
      num: '(04)',
      title: 'Experiência',
      totalLabel: 'Tempo total',
      cnpjLabel: 'CNPJ',
      presentLabel: 'Atual',
      companies: [
        {
          name: 'CAIXA Econômica Federal',
          cnpj: '00.360.305/0001-05',
          from: '06/05/2011',
          to: 'Atual',
          roles: [
            { from: '03/02/2014', to: 'Atual', role: 'Avaliador de Penhor' },
            {
              from: '11/02/2021',
              to: '02/05/2023',
              role: 'Substituto Eventual Gerente de Varejo',
            },
            { from: '08/04/2024', to: '19/04/2024', role: 'Gerente de Varejo S.E' },
            { from: '15/02/2024', to: '27/02/2024', role: 'Gerente de Varejo S.E' },
            { from: '08/09/2021', to: '17/09/2021', role: 'Gerente de Varejo S.E' },
            { from: '10/01/2013', to: '02/02/2014', role: 'Caixa Executivo' },
            { from: '06/05/2011', to: '09/01/2013', role: 'Técnico Bancário' },
          ],
        },
        {
          name: 'Sindicato dos Empregados em Estabelecimentos Bancários de Ponta Porã/MS',
          cnpj: '03.890.670/0001-19',
          from: '01/07/2024',
          to: 'Atual',
          roles: [
            {
              from: '01/07/2024',
              to: 'Atual',
              role: 'Desenvolvedor FullStack · Contrato de prestação de serviços',
            },
          ],
        },
        {
          name: 'Empresa de Apoio à Educação Douradense Ltda',
          cnpj: '08.989.598/0001-03',
          from: '01/08/2009',
          to: '20/04/2011',
          roles: [
            {
              from: '01/08/2009',
              to: '20/04/2011',
              role: 'Técnico de Manutenção Eletrônica · Professor de Informática',
            },
          ],
        },
      ],
    },
    edu: {
      num: '(05)',
      title: 'Educação Formal',
      statusOngoing: 'Cursando',
      statusDone: 'Concluído',
      dateOngoingLabel: 'Previsão de conclusão',
      dateDoneLabel: 'Conclusão',
      kindLabel: 'Tipo',
      workloadLabel: 'Carga horária',
      cnpjLabel: 'CNPJ',
      validationLabel: 'Validação',
      documentLabel: 'Diploma',
      items: [
        {
          status: 'ongoing',
          title: 'MBA em IA e Business Analytics',
          kind: 'Pós-Graduação Lato Sensu',
          institution: 'UNIGRAN Educacional',
          cnpj: '03.361.110/0001-77',
          date: '30/10/2026',
          workload: '464 horas',
        },
        {
          status: 'ongoing',
          title: 'Bacharelado em Engenharia de Software',
          kind: 'Bacharelado',
          institution: 'CESUMAR — Centro de Ensino Superior de Maringá Ltda',
          cnpj: '79.265.617/0001-99',
          date: '30/07/2028',
          workload: '2.980 horas',
        },
        {
          status: 'done',
          title: 'Bacharelado em Ciências Contábeis',
          kind: 'Bacharelado',
          institution: 'UNIGRAN Educacional',
          cnpj: '03.361.110/0001-77',
          date: '24/01/2026',
          workload: '3.210 horas',
          validation: 'https://unigran.webapp.abaris.com.br/diploma/0673.0673.329f03f0b1f5',
          url: 'docs/diploma_ciencias_contabeis.pdf',
        },
      ],
    },
    blog: {
      num: '(06)',
      title: 'Escrita recente',
      items: [
        {
          tag: 'Python',
          date: 'Mai 2026',
          t: 'Padrões de automação que sobrevivem ao tempo',
          x: 'Por que a maioria dos seus scripts quebram em 6 meses — e como estruturá-los para durar anos sem manutenção.',
        },
        {
          tag: 'Frontend',
          date: 'Abr 2026',
          t: 'Por que voltei a usar Django depois de 2 anos só em SPA',
          x: 'Sobre a falsa promessa do JS no servidor e quando o monolito com templates ainda vence.',
        },
        {
          tag: 'Dados',
          date: 'Mar 2026',
          t: 'Pandas é uma linguagem, não uma biblioteca',
          x: 'Aprendi mais sobre programação resolvendo CSVs no Pandas do que em qualquer livro de algoritmos.',
        },
        {
          tag: 'Carreira',
          date: 'Fev 2026',
          t: '11 anos no banco, 15 programando. O que aprendi sobre foco',
          x: 'Conciliar uma carreira pública estável com desenvolvimento independente exige um sistema, não disciplina.',
        },
      ],
      cta: 'Ler',
    },
    contact: {
      num: '(07)',
      title: 'Contato',
      big: ['VAMOS ', { em: 'construir ' }, 'algo', { outline: 'real' }],
      items: [
        { l: 'E-mail', v: 'contato@brunonyland.com', href: 'mailto:contato@brunonyland.com' },
        { l: 'GitHub', v: 'github.com/brunonyland', href: 'https://github.com/brunonyland' },
        {
          l: 'LinkedIn',
          v: 'linkedin.com/in/brunonyland',
          href: 'https://linkedin.com/in/brunonyland',
        },
        { l: 'Site', v: 'brunonyland.com', href: 'https://brunonyland.com' },
      ],
    },
    foot: { l: '© 2026 Bruno Nyland', r: 'Construído com Angular, GSAP e Three.js' },
    loader: {
      top1: 'BRUNO NYLAND',
      top2: 'PORTFOLIO 2026',
      foot1: 'CARREGANDO RECURSOS',
      foot2: 'v1.0',
    },
  },
  en: {
    nav: {
      about: 'About',
      skills: 'Stack',
      work: 'Work',
      xp: 'Experience',
      edu: 'Education',
      blog: 'Journal',
      contact: 'Contact',
    },
    hero: {
      eyebrow: 'Available for projects · 2026',
      role: 'Fullstack Developer',
      l1: 'BRUNO',
      l2: 'NYLAND',
      l3: 'FULLSTACK',
      l4: 'DEV',
      foot1l: 'Based in',
      foot1v: 'Brazil — UTC-3',
      foot2l: 'Main stack',
      foot2v: 'Python · TS · React',
      foot3l: 'Coding since',
      foot3v: '2010 / 15+ years',
      foot4: 'Scroll ↓',
      metaTitle: 'CURRENTLY',
      metaSub: 'Appraiser at CAIXA · Indie dev',
    },
    about: {
      num: '(01)',
      title: 'About',
      lead: [
        'I build web systems ',
        { em: 'from database to pixel' },
        '. 15+ years writing code, fluent in ',
        { em: 'Python, TypeScript, C++ and C#' },
        ', with a sharp focus on automation, data and end-to-end products.',
      ],
      p1: 'Accounting major, I’ve worked for 11 years as a pawn appraiser at CAIXA, Brazil’s federal bank. In parallel I build software independently — institutional sites, automation with Selenium and Requests, data pipelines with Pandas/NumPy and modern UIs in React/Angular.',
      p2: 'I like problems mixing technique, business and craft. I work on Django/Wagtail sites, FastAPI services, reactive apps and internal tools nobody sees — but everyone uses.',
      stats: [
        { n: '15', sup: '+', l: 'Years coding' },
        { n: '11', sup: 'yrs', l: 'CAIXA · Appraisal' },
        { n: '40', sup: '+', l: 'Projects shipped' },
        { n: '07', sup: 'stacks', l: 'Fluent languages' },
      ],
    },
    skills: {
      num: '(02)',
      title: 'Stack',
      groups: [
        { cat: 'Languages', items: ['Python', 'JavaScript / TypeScript', 'C++', 'C#'] },
        { cat: 'Frameworks', items: ['Django / Wagtail', 'FastAPI', 'React', 'Angular'] },
        {
          cat: 'Data & Automation',
          items: ['Pandas / NumPy', 'Selenium', 'Requests', 'ETL pipelines'],
        },
        { cat: 'Tooling', items: ['PostgreSQL', 'Docker', 'Git / CI', 'Linux'] },
      ],
    },
    work: {
      num: '(03)',
      title: 'Selected work',
      items: [
        {
          t: 'Appraisal System',
          y: '2025',
          k: 'Fintech / Internal',
          tags: ['Django', 'Postgres', 'Wagtail'],
          ph: 'Dashboard screenshot',
        },
        {
          t: 'Scraping Bot',
          y: '2024',
          k: 'Automation',
          tags: ['Python', 'Selenium', 'Pandas'],
          ph: 'Flow diagram',
        },
        {
          t: 'Catalog API',
          y: '2024',
          k: 'Backend',
          tags: ['FastAPI', 'Redis', 'Docker'],
          ph: 'API spec',
        },
        {
          t: 'React Dashboard',
          y: '2023',
          k: 'Frontend',
          tags: ['React', 'TS', 'D3'],
          ph: 'Panel mockup',
        },
        {
          t: 'ETL Pipeline',
          y: '2023',
          k: 'Data',
          tags: ['Python', 'Airflow', 'S3'],
          ph: 'Pipeline topology',
        },
        {
          t: 'Desktop Tooling',
          y: '2022',
          k: 'Internal',
          tags: ['C#', 'WPF'],
          ph: 'Tool screenshot',
        },
      ],
    },
    xp: {
      num: '(04)',
      title: 'Experience',
      totalLabel: 'Total time',
      cnpjLabel: 'CNPJ',
      presentLabel: 'Present',
      companies: [
        {
          name: 'CAIXA Federal Bank',
          cnpj: '00.360.305/0001-05',
          from: '06/05/2011',
          to: 'Present',
          roles: [
            { from: '03/02/2014', to: 'Present', role: 'Pawn Appraiser' },
            {
              from: '11/02/2021',
              to: '02/05/2023',
              role: 'Acting Retail Manager (substitute appointments)',
            },
            { from: '08/04/2024', to: '19/04/2024', role: 'Substitution: Retail Manager' },
            { from: '15/02/2024', to: '27/02/2024', role: 'Substitution: Retail Manager' },
            { from: '08/09/2021', to: '17/09/2021', role: 'Substitution: Retail Manager' },
            { from: '10/01/2013', to: '02/02/2014', role: 'Executive Teller' },
            { from: '06/05/2011', to: '09/01/2013', role: 'Bank Technician' },
          ],
        },
        {
          name: 'Bank Workers Union of Ponta Porã – MS',
          cnpj: '03.890.670/0001-19',
          from: '01/07/2024',
          to: 'Present',
          roles: [
            {
              from: '01/07/2024',
              to: 'Present',
              role: 'Fullstack Developer · Service contract',
            },
          ],
        },
        {
          name: 'Dourados Education Support Company Ltda',
          cnpj: '08.989.598/0001-03',
          from: '01/08/2009',
          to: '20/04/2011',
          roles: [
            {
              from: '01/08/2009',
              to: '20/04/2011',
              role: 'Electronics Maintenance Technician · IT Teacher',
            },
          ],
        },
      ],
    },
    edu: {
      num: '(05)',
      title: 'Formal Education',
      statusOngoing: 'In progress',
      statusDone: 'Completed',
      dateOngoingLabel: 'Expected completion',
      dateDoneLabel: 'Completed on',
      kindLabel: 'Degree',
      workloadLabel: 'Workload',
      cnpjLabel: 'CNPJ',
      validationLabel: 'Verify',
      documentLabel: 'Diploma',
      items: [
        {
          status: 'ongoing',
          title: 'MBA in AI & Business Analytics',
          kind: 'Postgraduate (Lato Sensu)',
          institution: 'UNIGRAN Educacional',
          cnpj: '03.361.110/0001-77',
          date: '30/10/2026',
          workload: '464 hours',
        },
        {
          status: 'ongoing',
          title: 'Bachelor of Software Engineering',
          kind: "Bachelor's Degree",
          institution: 'CESUMAR — Centro de Ensino Superior de Maringá Ltda',
          cnpj: '79.265.617/0001-99',
          date: '30/07/2028',
          workload: '2,980 hours',
        },
        {
          status: 'done',
          title: 'Bachelor of Accounting Sciences',
          kind: "Bachelor's Degree",
          institution: 'UNIGRAN Educacional',
          cnpj: '03.361.110/0001-77',
          date: '24/01/2026',
          workload: '3,210 hours',
          validation: 'https://unigran.webapp.abaris.com.br/diploma/0673.0673.329f03f0b1f5',
          url: 'docs/diploma_ciencias_contabeis.pdf',
        },
      ],
    },
    blog: {
      num: '(06)',
      title: 'Recent writing',
      items: [
        {
          tag: 'Python',
          date: 'May 2026',
          t: 'Automation patterns that survive time',
          x: 'Why most scripts break in 6 months — and how to structure them so they last for years untouched.',
        },
        {
          tag: 'Frontend',
          date: 'Apr 2026',
          t: 'Why I came back to Django after 2 years of pure SPA',
          x: 'On the false promise of JS on the server and when the monolith with templates still wins.',
        },
        {
          tag: 'Data',
          date: 'Mar 2026',
          t: 'Pandas is a language, not a library',
          x: 'I learned more about programming solving CSVs in Pandas than in any algorithms book.',
        },
        {
          tag: 'Career',
          date: 'Feb 2026',
          t: '11 years at the bank, 15 coding. What I learned about focus',
          x: 'Balancing a stable public-sector career with independent dev work demands a system — not discipline.',
        },
      ],
      cta: 'Read',
    },
    contact: {
      num: '(07)',
      title: 'Contact',
      big: ['LET’S ', { em: 'build ' }, 'something', { outline: 'real' }],
      items: [
        { l: 'E-mail', v: 'contato@brunonyland.com', href: 'mailto:contato@brunonyland.com' },
        { l: 'GitHub', v: 'github.com/brunonyland', href: 'https://github.com/brunonyland' },
        {
          l: 'LinkedIn',
          v: 'linkedin.com/in/brunonyland',
          href: 'https://linkedin.com/in/brunonyland',
        },
        { l: 'Website', v: 'brunonyland.com', href: 'https://brunonyland.com' },
      ],
    },
    foot: { l: '© 2026 Bruno Nyland', r: 'Built with Angular, GSAP and Three.js' },
    loader: {
      top1: 'BRUNO NYLAND',
      top2: 'PORTFOLIO 2026',
      foot1: 'LOADING ASSETS',
      foot2: 'v1.0',
    },
  },
};
